# -*- coding: utf-8 -*-
"""Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1anuSlFCUc0kEZB3oFMi7odWX_wkNvr34

#**************************************************
# FINAL PROJECT - ML, DL & NLP CAPSTONE
#**************************************************

In this project, I build a machine learning system to classify cybersecurity severity levels using text, numerical, and categorical data

### IMPORT LIBRARIES
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.metrics import precision_score, recall_score

from google.colab import files

uploaded = files.upload()

"""=========================
# LOAD DATASET
=========================

I upload and load the dataset into a pandas DataFrame
"""

df = pd.read_csv('healthcare_cybersecurity_10k.csv')
df.head()

"""=========================
#DATA CLEANING
=========================

I clean text data to make it ready for machine learning models
"""

def clean(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    return text

df["Description"] = df["Description"].apply(clean)

"""=========================
# DATA EXPLORATION
=========================

I explore the dataset to understand structure and missing values
"""

print("Shape:", df.shape)
print(df.dtypes)
print(df.describe())
print(df.info())

print("\nMissing values:")
print(df.isnull().sum())

print("\nClass balance:")
print(df["Severity"].value_counts())

print("\nClass balance (percentage):")
print(df["Severity"].value_counts(normalize=True))

"""=========================
# MISSING VALUES HANDLING
=========================

I fill missing values in categorical columns
"""

df["Weakness"] = df["Weakness"].fillna("Unknown")

df = df.dropna(subset=["Severity"])

df["CVSS_Score"] = df["CVSS_Score"].fillna(df["CVSS_Score"].median())
df["Attack_Vector"] = df["Attack_Vector"].fillna("Unknown")
df["Weakness"] = df["Weakness"].fillna("Unknown")

"""=========================
# FEATURES & TARGET
=========================

I split data into input features X and target label y
"""

X = df[["Description", "CVSS_Score", "Attack_Vector", "Weakness"]]
y = df["Severity"]

"""=========================
# TRAIN-TEST SPLIT
=========================

I split the dataset into training and testing sets
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""=========================
# PREPROCESSING PIPELINE
=========================

I convert text categorical and numeric data into numerical format
"""

preprocessor = ColumnTransformer([
    ("text", TfidfVectorizer(max_features=5000), "Description"),
    ("cat", OneHotEncoder(handle_unknown="ignore"), ["Attack_Vector", "Weakness"]),
    ("num", "passthrough", ["CVSS_Score"])
])

"""=========================
# MACHINE LEARNING MODELS
=========================

I train and compare 3 different ML models
"""

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=200),
    "KNN": KNeighborsClassifier(n_neighbors=5)
}

results = []

for name, model in models.items():

    pipe = Pipeline([
        ("prep", preprocessor),
        ("model", model)
    ])

    pipe.fit(X_train, y_train)
    preds = pipe.predict(X_test)

    acc = accuracy_score(y_test, preds)
    prec = precision_score(y_test, preds, average="weighted")
    rec = recall_score(y_test, preds, average="weighted")
    f1 = f1_score(y_test, preds, average="weighted")

    results.append({
        "Model": name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1": f1
    })

    print("\n********************")
    print(name)
    print(classification_report(y_test, preds))

    cm = confusion_matrix(y_test, preds)
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
    plt.title(f"{name} Confusion Matrix")
    plt.show()

"""=========================
# RESULTS TABLE
=========================

I compare all ML models using evaluation metrics
"""

results_df = pd.DataFrame(results)
results_df

print(results_df.sort_values("F1", ascending=False))

"""=========================
# LABEL ENCODING (NEURAL NETWORK)
=========================

I convert labels into numbers for neural network training
"""

le = LabelEncoder()
y_train_nn = le.fit_transform(y_train)
y_test_nn = le.transform(y_test)

"""=========================
# NEURAL NETWORK PREPROCESSING
=========================

I reuse preprocessing and convert data into numerical arrays
"""

nn_preprocessor = ColumnTransformer([
    ("text", TfidfVectorizer(max_features=5000), "Description"),
    ("cat", OneHotEncoder(handle_unknown="ignore"), ["Attack_Vector", "Weakness"]),
    ("num", "passthrough", ["CVSS_Score"])
])

X_train_nn = nn_preprocessor.fit_transform(X_train).toarray()
X_test_nn = nn_preprocessor.transform(X_test).toarray()

"""=========================
# BUILD NEURAL NETWORK
=========================

I create a deep learning model using Dense layers
"""

model = keras.Sequential([
    layers.Dense(128, activation="relu", input_shape=(X_train_nn.shape[1],)),
    layers.Dropout(0.3),
    layers.Dense(64, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(len(np.unique(y_train_nn)), activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

"""=========================
# TRAIN NEURAL NETWORK
=========================

I train the model and validate performance
"""

history = model.fit(
    X_train_nn, y_train_nn,
    validation_split=0.2,
    epochs=10,
    batch_size=32,
    verbose=1
)

"""=========================
# TRAINING CURVES
=========================

I plot accuracy and loss to check overfitting
"""

plt.plot(history.history["accuracy"], label="train")
plt.plot(history.history["val_accuracy"], label="val")
plt.title("Neural Network Accuracy")
plt.legend()
plt.show()

plt.plot(history.history["loss"], label="train_loss")
plt.plot(history.history["val_loss"], label="val_loss")
plt.title("Neural Network Loss")
plt.legend()
plt.show()

"""=========================
# MODEL EVALUATION
=========================

I evaluate neural network performance
"""

loss, acc = model.evaluate(X_test_nn, y_test_nn)
print("NN Accuracy:", acc)

nn_preds = model.predict(X_test_nn).argmax(axis=1)

"""I add results to comparison table"""

results_df.loc[len(results_df)] = [
    "Neural Network",
    accuracy_score(y_test_nn, nn_preds),
    precision_score(y_test_nn, nn_preds, average="weighted"),
    recall_score(y_test_nn, nn_preds, average="weighted"),
    f1_score(y_test_nn, nn_preds, average="weighted")
]

"""=========================
# FINAL COMPARISON
=========================
"""

print("FINAL COMPARISON TABLE:")
print(results_df.sort_values("F1", ascending=False))